### ISSUE TITLE
Allowing multiple arguments to be passed to log function.

### ISSUE THREAD

**Issue by howardroark** [latentflip/bows#20]
The current implementation of `console.log` allows you to pass it many arguments that you may wish to log...

```
console.log(string, array, object);
```

This is really nice because it lets you log many "types" in one function call.  It also prevents you from needing to concatenate strings.  I just thought it might be nice to have on the roadmap for this project... Which is really great as it stands!

**Comment by latentflip** [comment]
Hey @howardroark, this should work fine already as bows just uses console.log pre-bound with a couple of arguments.

**Comment by howardroark** [comment]
Well look at me making assumptions and not even trying...  Great work you have done here!
